[server]
port = 8501
maxUploadSize = 50
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = ""
serverPort = 8501
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E2E8F0"
font = "sans serif"
